
# Prevent Players from breaking and placing blocks in the Jump & Run area
protect-blocks: true

# Temporarily disables hunger while in Jump & Run
disable-hunger: true

# Temporarily disables Potion Effects while in Jump & Run
disable-potions: true

# Disables Ender Pearls inside the Jump & Run area
disable-ender-pearls: true

# Disables Wind Charges inside the Jump & Run area
disable-wind-charges: true

# ------------------------------ DO NOT manually change values below this line ------------------------------

pos1: null
pos2: null
config-version: 0
