
# Prevent Players from breaking and placing blocks in the Jump & Run area
protect-blocks: true

# Temporarily disables hunger while in Jump & Run
disable-hunger: true

# Temporarily disables Potion Effects while in Jump & Run
disable-potions: true

# Disables the use of projectiles like Ender Pearls, Wind Charges and Splash Potions during the Jump & Run
disable-projectiles: true

# Enables a bossbar which shows the current score during the Jump & Run
enable-bossbar: true

# Any block that can be coloured (wool, terracotta, glazed_terracotta, concrete, stained_glass)
block-material: 'wool'

# Shows a pass-through ghost block where the next block will generate
hologram-block: true

# Check for plugin updates
check-updates: true

database:
  # Choose either 'sqlite' or 'mysql'
  # DO NOT change this value unless you know what you are doing
  type: 'sqlite'

  # Only need to be set when a mysql database ist used
  credentials:
    host: ''
    database: ''
    username: ''
    password: ''

# ------------------------------ DO NOT manually change values below this line ------------------------------

config-version: 1
pos1: null
pos2: null
