
# Prevent Players from breaking and placing blocks in the Jump & Run area
protect-blocks: true

# Disable hunger while in Jump & Run
disable-hunger: true

# ------------------------------ DO NOT manually change values below this line ------------------------------

pos1: null
pos2: null
config-version: 0
