name: JumpNRun
version: '${version}'
description: An infinitely generating Jump & Run minigame
author: JoJjjo147

main: at.jonathans.jumpNRun.JumpNRun
api-version: '26.1.2'
load: POSTWORLD

softdepend: ["PlaceholderAPI"]

permissions:
  jumpnrun.admin:
    description: Admin commands
    default: op

commands:
  jumpnrun:
    usage: /<command>
